- package.json
- src/isEqual.js
- test/unit/isEqual-spec.js
> Fix string comparison

- src/array/union.js
- test/unit/array-spec.js
> fix: fix union object exception

- tsconfig.json
> Revert "fix: mocha ts definition"

- packages/matrix-util/__tests__/unit/matrix-spec.js
- packages/matrix-util/package.json
- packages/matrix-util/src/transform.ts
* transform(m, []) ，m 是 null 时对单位矩阵进行转换
* 补充单元测试
> feat(matrix): transfrom null matrix

- packages/matrix-util/package.json
> feat(version): update version of matrix-util

- package.json
> fix: missing @types/mocha definition for torch

- packages/util/__tests__/unit/memorize-spec.js
- packages/util/package.json
- packages/util/src/memoize.ts
> fix(memoize): when key is object, cache fail

- packages/path-util/__tests__/unit/get-arc-params-spec.js
- packages/path-util/__tests__/unit/path-2-segments-spec.js
- packages/path-util/package.json
- packages/path-util/src/get-arc-params.ts
- packages/path-util/src/index.ts
- packages/path-util/src/path-2-absolute.ts
- packages/path-util/src/path-2-segments.ts
- packages/path-util/src/path-intersection.ts
> feat(path): add path to segements and getArcParams

- packages/path-util/src/path-2-segments.ts
> feat(arc): default value of arc

- packages/path-util/__tests__/unit/intersect-spec.js
- packages/path-util/__tests__/unit/is-polygon-intersect-spec.js
- packages/path-util/__tests__/unit/line-intersect-spec.js
- packages/path-util/__tests__/unit/point-in-polygon-spec.js
- packages/path-util/package.json
- packages/path-util/src/get-line-intersect.ts
- packages/path-util/src/index.ts
- packages/path-util/src/is-polygons-intersect.ts
- packages/path-util/src/point-in-polygon.ts
* 将 isPointInPolygon 抽取到 path-util
* 将 line intersect 迁移到 path-util
* 实现 polygon 相交算法
> feat(intersect): polygon intersect

- packages/matrix-util/package.json
- packages/matrix-util/src/mat3.ts
- packages/matrix-util/src/vec2.ts
- packages/matrix-util/src/vec3.ts
> Revert "refactor: use gl-matrix as dependence"

- packages/matrix-util/package.json
> docs(version): revert

- packages/path-util/__tests__/unit/path-2-segments-spec.js
- packages/path-util/src/path-2-segments.ts
- 原先带 A 命令 path 的 endTangent 计算有误，应该做修正。
- Close antvis/g#488.
> fix(path-util): endTangent shoule be correct 

- packages/matrix-util/__tests__/unit/matrix-spec.js
- packages/matrix-util/package.json
- packages/matrix-util/src/mat3.ts
- packages/matrix-util/src/vec2.ts
> feat(transform): change left multiply

- packages/matrix-util/src/index.ts
详见 https://travis-ci.org/github/antvis/g/builds/683706515#L385
> fix(matrix): 修复部分 TypeScript 版本不支持 export * 的问题

- packages/color-util/package.json
- packages/dom-util/package.json
- packages/matrix-util/package.json
- packages/path-util/package.json
- packages/util/package.json
添加src文件夹到files用于sourceMap,
https://github.com/antvis/G2/issues/3053
> feat: add src to files for sourceMap

- packages/util/__tests__/unit/uniq-spec.js
- packages/util/package.json
- packages/util/src/group-to-map.ts
- packages/util/src/uniq.ts
> perf(uniq): perf fo uniq function

- packages/util/__tests__/unit/get-range-spec.js
- packages/util/__tests__/unit/max-spec.js
- packages/util/__tests__/unit/min-spec.js
- packages/util/package.json
- packages/util/src/max.ts
- packages/util/src/min.ts
> fix(min): min, max should use Math function

- packages/util/__tests__/unit/max-by-spec.js
- packages/util/__tests__/unit/min-by-spec.js
- packages/util/package.json
- packages/util/src/max-by.ts
- packages/util/src/min-by.ts
fixed https://github.com/antvis/G2Plot/issues/2616
> fix: maxBy minBy for empty data

- packages/util/__tests__/unit/get-ellipsis-text-spec.js
- packages/util/__tests__/unit/measure-text-width-spec.js
- packages/util/package.json
- packages/util/src/get-ellipsis-text.ts
- packages/util/src/index.ts
- packages/util/src/measure-text-width.ts
* measureTextWidth: 计算文本宽度
* getEllipsisText: 取得缩略文本
> feat(text): 添加了测算文本长度和取得文字缩略的方法

- packages/util/package.json
> csstype: devDependencies-> dependencies
> chore: csstype: devDependencies-> dependencies

- packages/path-util/__tests__/unit/catmull-rom-2-bezier-spec.js
- packages/path-util/package.json
- packages/path-util/src/catmull-rom-2-bezier.ts
- packages/util/src/get-ellipsis-text.ts
* 更新了 catmullRom2bezier 方法实现
* 完善了 @antv/util `getEllipsisText` 类型定义
> refactor(path-util): 更新了 catmullRom2bezier 方法实现

- package.json
- remove browser
- add sideEffects
> chore: add side effects

- package.json
- src/path/parse-path-string.ts
空格没必要用这么复杂的正则。另外会导致 terser（father 使用了 rollup-plugin-terser） 在压缩时跳过，导致压缩后代码缺失。
> fix: use a simpler space regexp

- src/path/util/segment-arc-factory.ts
- src/path/util/segment-cubic-factory.ts
- src/path/util/segment-quad-factory.ts
perf: optimize performance by removing spread array
> perf: optimize performance by removing spread array

- README.md
- __tests__/unit/math/is-point-in-polygon.spec.ts
- __tests__/unit/math/is-polygons-intersect.spec.ts
- package.json
- src/index.ts
- src/lodash/is-function.ts
- src/math/index.ts
- src/math/is-point-in-polygon.ts
- src/math/is-polygons-intersect.ts
> fix: tolerate async function #95
